### ISSUE TITLE
Error while rendering a template

### ISSUE THREAD

**Issue by holema** [YetiForceCompany/YetiForcePDF#33]
I upgraded my Yetiforce from 4.3 to 6.3 which worked quite well and all the PDF-Teplates where migrated correctly. I was so happy.
But now when I try to genereate a PDF I get this error which is thrown on all our templates.
```
Argument 1 passed to YetiForcePDF\Style\NumericValue::setValue() must be of the type string, null given, called in /var/www/html/www/web/YetiForce/vendor/yetiforce/yetiforcepdf/lib/Style/Normalizer/Normalizer.php on line 92.

Stacktrace:
vendor/yetiforce/yetiforcepdf/lib/Style/NumericValue.php(129)
#0 vendor/yetiforce/yetiforcepdf/lib/Style/Normalizer/Normalizer.php(92): YetiForcePDF\Style\NumericValue->setValue(NULL)
#1 vendor/yetiforce/yetiforcepdf/lib/Style/Normalizer/Normalizer.php(255): YetiForcePDF\Style\Normalizer\Normalizer->getNumberValues('')
#2 vendor/yetiforce/yetiforcepdf/lib/Style/Normalizer/BorderWidth.php(30): YetiForcePDF\Style\Normalizer\Normalizer->normalizeMultiValues(Array, '')
#3 vendor/yetiforce/yetiforcepdf/lib/Style/Normalizer/Border.php(49): YetiForcePDF\Style\Normalizer\BorderWidth->normalize('')
#4 vendor/yetiforce/yetiforcepdf/lib/Style/Style.php(1458): YetiForcePDF\Style\Normalizer\Border->normalize('', 'border')
#5 vendor/yetiforce/yetiforcepdf/lib/Style/Style.php(612): YetiForcePDF\Style\Style->parse()
#6 vendor/yetiforce/yetiforcepdf/lib/Layout/Box.php(342): YetiForcePDF\Style\Style->init()
#7 vendor/yetiforce/yetiforcepdf/lib/Layout/BlockBox.php(352): YetiForcePDF\Layout\Box->setStyle(Object(YetiForcePDF\Style\Style))
#8 vendor/yetiforce/yetiforcepdf/lib/Layout/ElementBox.php(253): YetiForcePDF\Layout\BlockBox->appendTableWrapperBox(Object(DOMElement), Object(YetiForcePDF\Html\Element), Object(YetiForcePDF\Style\Style), NULL)
#9 vendor/yetiforce/yetiforcepdf/lib/Html/Parser.php(228): YetiForcePDF\Layout\ElementBox->buildTree()
#10 vendor/yetiforce/yetiforcepdf/lib/Document.php(860): YetiForcePDF\Html\Parser->parse()
#11 vendor/yetiforce/yetiforcepdf/lib/Document.php(876): YetiForcePDF\Document->parse()
#12 app/Pdf/YetiForcePDF.php(498): YetiForcePDF\Document->render()
#13 modules/Vtiger/actions/PDF.php(195): App\Pdf\YetiForcePDF->output('Anordnung_Verke...', 'D')
#14 app/Controller/ExposeMethod.php(68): Vtiger_PDF_Action->generate(Object(App\Request))
#15 app/Controller/ExposeMethod.php(81): Vtiger_PDF_Action->invokeExposedMethod('generate', Object(App\Request))
#16 include/main/WebUI.php(188): Vtiger_PDF_Action->process(Object(App\Request))
#17 index.php(26): Vtiger_WebUI->process(Object(App\Request))
#18 public_html/index.php(13): require('/var/www/html/w...')
#19 {main}
```

I´m realy lost with this error, because in our PDF-Template isn`t any border-width defined.

**Comment by rskrzypczak** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/issues/14704
Remove the styles from the template that is possibly causing the problem, one by one.
